---
language: ruby
cache: bundler
rvm:
  - 1.8.7
  - 1.9.8
  - 2.1.8
  - 2.2.4
  - 2.3.1
  - 2.4.0
  - 2.5.1
  - 2.6.4
before_install: gem install bundler
script:
  - bundle install — jobs=3 — retry=3
  - bundle exec rake spec